### PR TITLE
Merge LobsterDog's image comparison test into master

### PR DESCRIPTION
**Pull request by JakeCover**

### CODE REVIEW

**Comment by JakeCover** [comment]
@ALobsterDog I'd really like to add this to the project! If you could work on it some more that would be great!

**Comment by ALobsterDog** [comment]
I'd be happy to. There's only one real change in this commit: the image assertion. all the other changes are from my autolinter, so you can take them or leave them.

I was trying to think of more assertions to add, did you have any broad-strokes goals or specific features in mind for the project?

add me on discord if you like. I'm Dinkus#8126.

**Comment by ALobsterDog** [comment]
right now I'm working on testing joining a voice channel, but i'll be away for the weekend so won't be able to work on it until next week.

**Comment by JakeCover** [comment]
> Autolinter

I'll run Black on it before I merge it. Would you mind using that for this project? It is similar to what you are using, might be it.


> Adding image assertion

Make sure you add a demo of each assertion to example_tester.py if you can, I'll add the rest of the current ones in master soon. Looks neat!


> More assertions

Whatever you think would be useful. I'll make a github project soon to track features, tracking them with a check box in the readme isn't going to work much longer. If you have ideas right now, just add them to the Checklist in the readme on your fork until I get the project going


> Voice

Sounds useful, plz do!


> Broad goals

I would like to add some setup teardown eventually, but that would probably be really difficult. I haven't given it much thought yet.


 > Discord

Sure, I might make a server for this sometime this weekend. I'll add you rn.

Thanks!

**Comment by ALobsterDog** [comment]
Hey Jake,

Just got back from vacation and excited to contribute. I see you've added a CLI, which is just fantastic, I'll have to test that out soon as I can. 

For now I'm going to add an example test for the image assertion and get that committed asap. will likely get to it this afternoon. 

voice will be trickier, but it's next on my docket.

**Comment by ALobsterDog** [comment]
@JakeCover image assertion pending your approval :)

**Comment by JakeCover** [comment]
Thanks a ton! I will add a check to `attachment.height is None` rather than `attachment is None` (checks that attachment is image, not PDF or Video), but other than that it's great. Merging now.

**Pull request merged**
