### PR TITLE
Clean up and test the refactor before merging into develop

### PR DESCRIPTION
**Pull request by JakeCover**
Hey all, 
I really should have done this in #5 , but I merged that before fully testing. Here, I am going to add more things before I merged it in. Notably: 
- [x] Documentation on what each file is for
- [x] Thorough testing of each file, will use code coverage or something to test
- [x] Possibly even more refactoring? May break things down into folders now
- [x] Confirm that this can be made into a package and still work

### CODE REVIEW

**Comment by ALobsterDog** [comment]
@JakeCover I have those docstrings ready, can I get push access to this branch?

**Comment by JakeCover** [comment]
> @JakeCover I have those docstrings ready, can I get push access to this branch?

Shoot! I just added some dockstrings, can you add yours to make them better? You are now a collaborator, sorry I forgot! .

**Comment by JakeCover** [comment]
Thank you for fixing that on 67eda55. Also, 5bb0c51 is a MUCH more elegant solution to my quick and dirty approach. I explained some of my reasoning in https://github.com/JakeCover/distest/issues/8#issuecomment-496264079, but I wrote most of that before seeing this change. Since some of these changes are a bit complicated (977b3c9), although a huge improvement, make sure you describe the ways things now work in docstrings. Thank you!

**Comment by ALobsterDog** [comment]
Just noticed ``_run_by_predicate`` isnt documented and you're right its not
immediately obvious what it does. I'll doc it this afternoon.

**Comment by JakeCover** [comment]
Ok, I have it working. The tests pass! I'm pretty sure the other Travis CI is a duplicate and should be removed eventually.

**Comment by ALobsterDog** [comment]
Great, what next? merge into develop?

**Comment by JakeCover** [comment]
Yeah, I'll do that.

**Pull request merged**
