### PR TITLE
Add documentation inline, generate the documentation, host somewhere

### PR DESCRIPTION
**Pull request by JakeCover**
- [ ] Add Documentation (subtask this more)
- [x] Generate the Documentation (subtask)
- [x] Come up with and implement a hosting solution (subtask)
    - Readthedocs? Heroku? Github Pages?
- [x] Add tests for documentation
- [x] Add autobuilding for documentation

Just put the commits here, we realistically need to do it in this order anyway.

@ALobsterDog you seem to be taking the lead on this, so if you want to add your commits here, that would be great. I'll get started soonly.

### CODE REVIEW

**Comment by JakeCover** [comment]
I am aware of the pile of todos I added, I will be turning those into v2.0 milestone issues before merging this, I was just on a plane and couldn't turn them into issues when I ran into the problems.

**Comment by ALobsterDog** [comment]
I was working on this last night and was having a lot of trouble getting sphinx to import submodules (kept giving errors like "no module called distest.interface" and I can't work out if i'm being dumb or not. You said you got it working? I'll pull this and check it out on my machine later today.

**Comment by JakeCover** [comment]
Sorry about the delay! I'm traveling rn and was super jetlagged the last two days, but I can probably help now. Are you on Windows or Linux? I made some changes to the makefile but not to the .bat file, I can try to translate them over when I get back to a laptop.

**Comment by ALobsterDog** [comment]
readthedocs is the best option for sure.

**Comment by ALobsterDog** [comment]
https://distest.readthedocs.io/en/feature-add_documentation/

first docs build

**Comment by JakeCover** [comment]
Ok I left this one here for a while, but now it's done.

**Pull request merged**
