### PR TITLE
Update validate_discord_token.py

### PR DESCRIPTION
**Pull request by sean-keisuke**
Discord Token now can have a prefix starting with the Letter O.

### CODE REVIEW

**Comment by JakeCover** [comment]
Whoops, thought I responded to this earlier! Thanks a million, I was wondering what went wrong here but this totally makes sense. I have 3 midterms this week, but I'll run the tests on this and get it merged in as soon as I can.

Also, are you confident that they just added the letter O prefix and not others as well?

**Comment by sean-keisuke** [comment]
> Whoops, thought I responded to this earlier! Thanks a million, I was wondering what went wrong here but this totally makes sense. I have 3 midterms this week, but I'll run the tests on this and get it merged in as soon as I can.
> 
> Also, are you confident that they just added the letter O prefix and not others as well?

I am like 90% confident. I looked over some of the discord token generator documentations and it seems like they only support prefixes M,N and O

**Comment by sean-keisuke** [comment]
@JakeCover it would be awesome if someone can get this in. We would love to use this for our project!

**Comment by JakeCover** [comment]
Oh, so sorry about that! School really caught up to me this week. Expect a new version in just a bit

**Comment by JakeCover** [comment]
Ok you should be good to update to 0.6.1. Thanks for fixing that!

**Pull request merged**
